version: '3.8'

services:
  ai-text-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
  test:
    build: .
    command: pytest
    env_file:
      - .env